# OpenCV
opencv is a library of programming functions mainly aimed at real-time computer vision. We will use it to process images and videos. OpenCV was originally developed by Intel and is now maintained by Willow Garage and ItSeez. opencv-python is the Python API of OpenCV. It combines the best qualities of OpenCV C++ API and Python language.

## Installation

In [2]:
%pip install opencv-python

  Obtaining dependency information for opencv-python from https://files.pythonhosted.org/packages/8a/6f/8aa049b66bcba8b5a4dc872ecfdbcd8603a96704b070fde22222e479c3d7/opencv_python-4.8.0.76-cp37-abi3-macosx_10_16_x86_64.whl.metadata
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.7/54.7 MB 11.0 MB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.


In [14]:
# import opencv
import cv2
# import numpy
import numpy as np

## Mat - the basic image container
### Goal
We have multiple ways to aquire digital images from the real world: digital cameras, scanners, computed tomography, etc. In every case what we see are images. However, when transferred to a computer, the images are represented as a matrix of numbers. In this section we will learn how to use the Mat class to represent images in OpenCV.

### Basics
The Mat class represents a matrix. It is a 2D array, with each element of the array corresponding to a pixel in the image. The Mat class is defined in the Core module of OpenCV. The Mat class is a template class that can take any number of channels. The Mat class is defined as follows:

Mat< _Tp > class cv::Mat

The Mat class can be used to store photo in python as follows:

In [6]:
# create a Mat object to store an image
img1 = cv2.imread('images/cat.webp')

# use the copy method to create a new image
img2 = img1

# modify the img1
img1[0, 0] = [255, 255, 255]

# what is the difference between the four images?
print(img1[0, 0])
print(img2[0, 0])
# img1 and img2 are the same object


[255 255 255]
[255 255 255]


What we can see that img1 and img4 are the same image, but the header is different. The real interesting is that you can headers which refer to subsection of the fall data.


In [7]:
# subsection of an image
img3 = img1[100:200, 200:300]
img3[0, 0] = [0, 0, 0]
print(img1[100, 200])
print(img3[0, 0])


[0 0 0]
[0 0 0]


Now we may wonder - if the matrix itself may belong to multiple Mat objects, how do we know when to deallocate the matrix? The answer is simple - the matrix will be deallocated when the last Mat object referencing it is gone. In other words, the matrix will be deallocated when the header is gone. For example, the following code will deallocate the matrix pointed by img1:

In [8]:
# delocate the memory
del img1, img2, img3

Sometimes we may want to copy the data of a matrix to another matrix. In this case, we can use the copy() method of the Mat class. For example, the following code will copy the data of img1 to img2:

In [12]:
# clone and copy
img1 = cv2.imread('images/cat.webp')
img2 = img1.copy()

# modify the img1
img1[0, 0] = [255, 255, 255]

# what is the difference between the four images?
print(img1[0, 0])
print(img2[0, 0])
# img1 and img2 are different objects
del img1, img2

[255 255 255]
[244 243 241]


### Storing methods
This is about how the pixel value is stored. We can select the color space and the data type of the pixel value. The color space refers to how we combine color components to create colors. The simplest color space is the grayscale color space. In this color space, each pixel is represented by a single number. The number represents the intensity of the pixel. The higher the number, the brighter the pixel. The grayscale color space is also called the intensity color space.

The RGB color space is the most common color space. In this color space, each pixel is represented by three numbers. The three numbers represent the intensity of the red, green and blue components of the pixel. The higher the number, the brighter the component. To code the transparency of a color a fourth component is added. This color space is called RGBA.

There are, however, many other color systems, each with their own advantages:
        RGB - Red, Green, Blue (default) : however OpenCV stores them in BGR order
        HSV - Hue, Saturation, Value and HLS - Hue, Lightness, Saturation : are more natural way to think about colors, we may discard the value or last component to make more robust to lighting changes
        YUV - Luminance, Chrominance : is used in video systems, where Y is the luminance component and U and V are the chrominance components
        YCrCb - Luminance, Red Chrominance, Blue Chrominance  : used for JPEG and MPEG images
        CIE - L*a*b* - Lightness, Red-Green, Blue-Yellow : is designed to approximate human vision, is perceptually uniform color space, meaning that the difference between two colors is perceptually uniform, which come handy if we need to measure distance given two colors

The data type of the pixel value can be unsigned char, signed char, unsigned short, signed short, int, float, double, etc. The data type of the pixel value is specified by the template parameter of the Mat class. Note that increasing the data type will increase the memory required to store the pixel value. 

Examples of how to create a Mat object with different color spaces and data types are shown below:


In [16]:
# images with different color spaces (BGR, GRAY, HSV) and different data types (uint8, float32 , char)
img = cv2.imread('images/cat.webp')
print(img.shape)
print(img.dtype)

# convert the image to gray scale
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print(img_gray.shape)
print(img_gray.dtype)

# convert the image to HSV
img_hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
print(img_hsv.shape)
print(img_hsv.dtype)

# convert the image to float32
img_float32 = img.astype(np.float32)
print(img_float32.shape)
print(img_float32.dtype)

# convert the image to uint8
img_uint8 = img.astype(np.uint8)
print(img_uint8.shape)
print(img_uint8.dtype)

# convert the image to char
img_char = img.astype(np.int8)
print(img_char.shape)
print(img_char.dtype)


# delocate the memory
del img, img_gray, img_hsv, img_float32, img_uint8, img_char

(900, 600, 3)
uint8
(900, 600)
uint8
(900, 600, 3)
uint8
(900, 600, 3)
float32
(900, 600, 3)
uint8
(900, 600, 3)
int8


### Creating Mat objects explicitly
We can use cv::imwrite() to write a matrix to an image file. The first parameter is the name of the file. The second parameter is the matrix to be written. The third parameter is an optional parameter specifying the compression method. The default value is 0, which means that the image is not compressed. The following code writes the matrix img1 to the file img1.png:

In [17]:
# imwrite method
img = cv2.imread('images/cat.webp')
cv2.imwrite('images/cat.png', img)

# delocate the memory
del img

However, for debugging purposes, it is convenient to see actual values of the matrix. 

In [30]:
# 2 by 2 image with 0,0,255 color on all pixels
img = np.full((2, 2, 3), (0, 0, 255), dtype=np.uint8)
print("img shape with 0,0,255 color on all pixels")
print(img)
# 2x2 image with 2 channels
print("2x2 image with 2 channels")
img = np.full((2, 2, 2), 255, dtype=np.uint8)
print(img)
# zeros ones and eye
## 2x2 image with 3 channels and all pixels are 0
print("2x2 image with 3 channels and all pixels are 0")
img = np.zeros((2, 2, 3), dtype=np.uint8)
print(img)
## 2x2 image with 3 channels and all pixels are 1
print("2x2 image with 3 channels and all pixels are 1")
img = np.ones((2, 2, 3), dtype=np.uint8)
print(img)
## eye matrix with 2x2 and 1 channel and all pixels are 1 on the diagonal
print("eye matrix with 2x2 and 1 channel and all pixels are 1 on the diagonal")
img = np.eye(2, dtype=np.uint8)
print(img)

del img



img shape with 0,0,255 color on all pixels
[[[  0   0 255]
  [  0   0 255]]

 [[  0   0 255]
  [  0   0 255]]]
2x2 image with 2 channels
[[[255 255]
  [255 255]]

 [[255 255]
  [255 255]]]
2x2 image with 3 channels and all pixels are 0
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
2x2 image with 3 channels and all pixels are 1
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
eye matrix with 2x2 and 1 channel and all pixels are 1 on the diagonal
[[1 0]
 [0 1]]


In [29]:
# clone a row
img = cv2.imread('images/cat.webp')
img_clone = img[0].copy()
img_clone[0] = [255, 255, 255]
print('row')
print(img[0, 0])
print(img_clone[0])

# clone a column
img_clone = img[:, 0].copy()
img_clone[0] = [255, 255, 255]
print('column')
print(img[0, 0])
print(img_clone[0])

del img, img_clone



row
[244 243 241]
[255 255 255]
column
[244 243 241]
[255 255 255]


### Output format
In python we can use the print() function to print the matrix. However, the output is not very readable. We can use the format() method of the Mat class to print the matrix in a more readable format. The format() method takes a format specifier as a parameter. The format specifier is a string that specifies how the matrix should be formatted. The format specifier is similar to the format specifier used in the printf() function of the C language.


In [31]:
## How to scan an image, lookup table, and time measurement
### Goal
